### ISSUE TITLE
Authenticated socks proxy

### ISSUE THREAD

**Issue by bytadaniel** [Kaciras/fetch-socks#1]
Hi! Could you please show how to provide authenticated socks proxy requests with your package?

**Comment by bytadaniel** [comment]
I mean
What if I have something like that: "{ip}:{port=3004}:{username}:{password}"

**Comment by Kaciras** [comment]
The `userId` and `password` properties can be used to provide auth info.

```javascript

const dispatcher = socksDispatcher({
    type: 5,
    host: "ip",
    port: 3004,
    userId: "username",
    password: "password",
});
const response = await fetch("http://example.com", { dispatcher });
```
